const axios = require('axios');
require('dotenv').config();

/**
 * Retoucher Agent
 * Acts as an aesthetic auditor and quality controller.
 * Migrated to OpenRouter to support advanced Vision models for UI/UX audits.
 */
class RetoucherAgent {
    constructor() {
        this.apiKey = process.env.OPENROUTER_API_KEY;
        this.model = process.env.OPENROUTER_MODEL || 'google/gemini-2.0-flash-001';
        
        if (!this.apiKey) {
            throw new Error('OPENROUTER_API_KEY is not defined in environment variables.');
        }
    }

    /**
     * Refines and polishes the raw HTML using targeted edits.
     * @param {string} rawHtml - The HTML string generated by the Creator agent
     * @param {Object} business - The business details
     * @returns {Promise<string>} Polished HTML string
     */
    async retouchWebsite(rawHtml, business) {
        console.log(`[Retoucher] Auditing website for: ${business.name} using ${this.model}...`);

        const systemPrompt = `You are a world-class UI/UX Designer and strict Aesthetic Auditor.
Your job is to audit HTML/Tailwind code to find duplicate assets, broken maps, or generic UI patterns and suggest premium upgrades.

ESTHETIC RULES:
1. **Remove Broken Maps**: If you see a Google Maps iframe or generic "Red X" style placeholders, replace them with a high-quality relevant hero image from loremflickr.
2. **No Duplicate Media**: Scan for identical image URLs. Replace duplicates with: https://loremflickr.com/1200/800/{industry}?random={n}
3. **Premium UI**: Replace basic Tailwind classes (bg-white, shadow-md) with premium versions (glassmorphism, subtle gradients, smooth transitions).

OUTPUT FORMAT:
Return ONLY a valid JSON array of objects. No markdown.
[
  { "old": "exact_html_string", "new": "improved_html_string" }
]`;

        const userPrompt = `
Business: ${business.name}
Industry: ${(business.types || []).join(', ')}

HTML to Audit:
${rawHtml.substring(0, 15000)} // Limiting to avoid context issues
`;

        try {
            const response = await axios.post('https://openrouter.ai/api/v1/chat/completions', {
                model: this.model,
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt }
                ],
                response_format: { type: 'json_object' }
            }, {
                headers: {
                    'Authorization': `Bearer ${this.apiKey}`,
                    'Content-Type': 'application/json'
                },
                timeout: 50000 
            });

            const content = response.data.choices[0].message.content;
            
            // Extract the array from the JSON object if the model wrapped it
            let edits = [];
            const parsed = typeof content === 'string' ? JSON.parse(content) : content;
            edits = Array.isArray(parsed) ? parsed : (parsed.edits || Object.values(parsed)[0]);

            if (!Array.isArray(edits)) {
                console.warn("[Retoucher] Model didn't return an array. Skipping.");
                return rawHtml;
            }

            console.log(`[Retoucher] Applying ${edits.length} aesthetic enhancements...`);

            let finalHtml = rawHtml;
            for (const edit of edits) {
                if (edit.old && edit.new) {
                    // Using split/join for global replace of exact strings safely
                    finalHtml = finalHtml.split(edit.old).join(edit.new);
                }
            }

            return finalHtml;
        } catch (error) {
            console.error(`[Retoucher] Audit failed: ${error.message}`);
            return rawHtml; 
        }
    }
}

module.exports = RetoucherAgent;
